### ISSUE TITLE
[BUG] spf exists and ipv6 uses invalid query

### ISSUE THREAD

**Issue by lilmike** [rspamd/rspamd#3625]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
When using exists with macros for ip (specifically %{ir}), rspamd uses an invalid dns query for the lookup. I noticed this when using an spf record that was "v=spf1 exists:%{ir}.ip.%{h}.helo.spf.mwtd.net exists:%{l}.%{o}.sender.%{ir}.ip.%{h}.helo.spf.mwtd.net ~all" and rspamd looked up a dns query including the full ipv6 address with colon notation, not dot notation and not reversed. The lookup was "thefam.number89.net.sender.2605:2700:0:12:1979::fa0.ip.hurricane.the-brannons.com.helo.spf.mwtd.net" when it should have been "thefam.number89.net.sender.0.a.f.0.0.0.0.0.0.0.0.0.9.7.9.1.2.1.0.0.0.0.0.0.0.0.7.2.5.0.6.2.ip.hurricane.the-brannons.com.helo.spf.mwtd.net". I'm not sure if this is a problem with ipv4 and a reversed notation lookup, but yeah.

logs:

2021-01-27 12:23:29 #1143302(normal) <bb2db6>; spf; parse_spf_redirect: resolve redirect spf.mwtd.net
2021-01-27 12:23:29 #1143302(normal) <bb2db6>; spf; spf_record_dns_callback: got redirection record for spf.mwtd.net: 'v=spf1 exists:%{ir}.ip.%{h}.helo.spf.mwtd.net exists:%{l}.%{o}.sender.%{ir}.ip.%{h}.helo.spf.mwtd.net ~all'
2021-01-27 12:23:29 #1143302(normal) <bb2db6>; spf; expand_spf_macro: disable SPF caching as there is macro expansion
2021-01-27 12:23:29 #1143302(normal) <bb2db6>; spf; parse_spf_exists: resolve exists 2605:2700:0:12:1979::fa0.ip.hurricane.the-brannons.com.helo.spf.mwtd.net
2021-01-27 12:23:29 #1143302(normal) <bb2db6>; spf; parse_spf_exists: resolve exists thefam.number89.net.sender.2605:2700:0:12:1979::fa0.ip.hurricane.the-brannons.com.helo.spf.mwtd.net
2021-01-27 12:23:29 #1143302(normal) <bb2db6>; spf; parse_spf_all: parsed all elt
2021-01-27 12:23:29 #1143302(normal) <bb2db6>; spf; rspamd_spf_process_reference: domain number89.net is redirected to spf.mwtd.net
2021-01-27 12:23:29 #1143302(normal) <bb2db6>; spf; spf.lua:144: got spf results: 0 flags, nil err
2021-01-27 12:23:29 #1143302(normal) <bb2db6>; spf; spf.lua:150: checked ip 2605:2700:0:12:1979::fa0: result=0, flag_or_policy=nil, error_or_addr={[result] = 1, [addr] = any, [str] = all, [flags] = 2072}

### Steps to Reproduce

1. Set up an spf record with an exists: type that included %{ir}.
2. Send an email from an ipv6 host to another ipv6 host, and check the spf debug logs.
3. Notice that the lookup contains the ipv6 address in colon notation and not reversed.

**Expected behavior**
The lookup should have included a reversed ipv6 address in dot notation instead of an ipv6 address in colon notation.

### Versions
2.6, arch linux rolling latest, AMD EPYC 7402P 24-Core Processor
 (virtualized)

**Comment by membero** [comment]
I have tested the patch. With it the spf lookup of deutschepost.de is working. With rspamd 2.6/2.7 rspamadm dnstool says "no record".

**Comment by lilmike** [comment]
This issue definitely still exists. Thanks.
-- 
Michael Taboada, Creator of Games. Does that make me a god, well, sorta.
My pgp key: 79BC390E8864CD71305D4DD606CD2197A6EE5ED7
My website: https://michaels.world
2MB website: https://2mb.games
Don't believe everything you read on the internet. I might not be real, you might not be real, and this email certainly isn't real.
Sent from my internet connected...
stationary bicycle

**Comment by lilmike** [comment]
This issue still exists.
-Michael.

-- 
Sorry about the test, it's just a me thing.
Michael Taboada, Creator of Games. Does that make me a god, well, sorta.
My pgp key: 79BC390E8864CD71305D4DD606CD2197A6EE5ED7
My website: https://michaels.world
2MB website: https://2mb.games
Don't believe everything you read on the internet. I might not be real, you might not be real, and this email certainly isn't real.
Sent from my newfangled...
stationary bicycle

**Comment by vstakhov** [comment]
I believe it is fixed in the master branch.

**Comment by membero** [comment]
Hello,

in rspamd 3.0 the problem still exists:

rspamadm dnstool spf -d deutschepost.de
Cannot get SPF record: no SPF record

**Comment by MartB** [comment]
This is supposedly already part of 3.1 but the `deutschepost.de` thing still doesnt work, opening another issue.
