### ISSUE TITLE
[BUG] dmarc reports sent in version 3.0 doesn't include dkim on auth results

### ISSUE THREAD

**Issue by aalmenar** [rspamd/rspamd#3877]
After upgrading from rspam 2.7 to 3.0, updating dmarc configuration according to upgrade notes in 3.0 now the dmarc reports doesn't include in the reports between <auth_results> the dkim status:

Email sent had this after being received:

Authentication-Results: mx1.domainrcpt.com;
	dkim=pass header.d=domainsender.com header.s=20210616143714114 header.b=MwL64kqo;
	spf=pass (mx1.domainrcpt.com: domain of user@domainsender.com designates x.x.x.x as permitted sender) smtp.mailfrom=user@domainsender.com;
	dmarc=pass (policy=reject) header.from=domainsender.com

But in the XML generated for reports, you can see a gap in auth_results node:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<feedback>
  <report_metadata>
    <org_name>DMARC Report</org_name>
    <email>dmarc@reports.domainrcpt.com</email>
    <report_id>domainsender.com.1630524024.1630524215</report_id>
    <date_range>
      <begin>1630524024</begin>
      <end>1630524215</end>
    </date_range>
  </report_metadata>
  <policy_published>
    <domain>domainsender.com</domain>
    <adkim>r</adkim>
    <aspf>r</aspf>
    <p>reject</p>
    <sp>none</sp>
    <pct>100</pct>
  </policy_published>
<record>
  <row>
    <source_ip>x.x.x.x</source_ip>
    <count>1</count>
    <policy_evaluated>
      <disposition>none</disposition>
      <dkim>pass</dkim>
      <spf>pass</spf>
      
    </policy_evaluated>
  </row>
  <identifiers>
    <header_from>domainsender.com</header_from>
  </identifiers>
  <auth_results>
    
    
    
    <spf>
      <domain>domainsender.com</domain>
      <result>pass</result>
    </spf>
  </auth_results>
</record>
</feedback>
```

So probably a bug, but i could not find where the issue is.

my dmarc.conf looks like this:

```
servers = "x.x.x.x";

  reporting {
    # Required attributes
    enabled = true; # Enable reports in general
    email = 'dmarc@reports.domainrcpt.com'; # Source of DMARC reports
    domain = 'domainrcpt.com'; # Domain to serve
    org_name = 'DMARC Report'; # Organisation
    # Optional parameters
    report_local_controller = false; # Store reports for local/controller scans (for testing only)
    helo = 'reports.domainrcpt.com'; # Helo used in SMTP dialog
    smtp = '127.0.0.1'; # SMTP server IP
    smtp_port = 25; # SMTP server port
    from_name = 'dmarc@reports.domainrcpt.com'; # SMTP FROM
    msgid_from = 'dmarc'; # Msgid format
    max_entries = 1k; # Maxiumum amount of entries per domain
    keys_expire = 2d; # Expire date for Redis keys
    #only_domains = '/path/to/map'; # Store reports merely from those domains
  }
```

**Comment by vstakhov** [comment]
It should be fixed now, thanks!

**Comment by aalmenar** [comment]
@vstakhov tried your changes but the xml is still missing the auth_data on dkim even though that dkim has passed, so the reports still are innacurate or incomplete.

**Comment by vstakhov** [comment]
I can definitely see that if running `rspamadm dmarc_report -n -v`

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<feedback>
  ...
<record>
  <row>
    <source_ip>8.8.8.8</source_ip>
    <count>1</count>
    <policy_evaluated>
      <disposition>quarantine</disposition>
      <dkim>fail</dkim>
      <spf>fail</spf>
    </policy_evaluated>
  </row>
  <identifiers>
    <header_from>highsecure.ru</header_from>
  </identifiers>
  <auth_results>
    <spf>
      <domain></domain>
      <result>none</result>
    </spf>
  </auth_results>
</record>
<record>
  <row>
    <source_ip>8.8.8.8</source_ip>
    <count>2</count>
    <policy_evaluated>
      <disposition>quarantine</disposition>
      <dkim>fail</dkim>
      <spf>fail</spf>
    </policy_evaluated>
  </row>
  <identifiers>
    <header_from>highsecure.ru</header_from>
  </identifiers>
  <auth_results>
    <dkim>
      <domain>highsecure.ru</domain>
      <result>fail</result>
    </dkim>
    <spf>
      <domain></domain>
      <result>none</result>
    </spf>
  </auth_results>
</record>
</feedback>
```

**Comment by aalmenar** [comment]
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<feedback>
  <report_metadata>
    <org_name>DMARC Report</org_name>
    <email>dmarc@reports.rcptdomain.com</email>
    <report_id>senderdomain.com.1630568989.1630682508</report_id>
    <date_range>
      <begin>1630568989</begin>
      <end>1630682508</end>
    </date_range>
  </report_metadata>
  <policy_published>
    <domain>senderdomain.com</domain>
    <adkim>r</adkim>
    <aspf>r</aspf>
    <p>reject</p>
    <sp>none</sp>
    <pct>100</pct>
  </policy_published>
<record>
  <row>
    <source_ip>x.x.x.x</source_ip>
    <count>1</count>
    <policy_evaluated>
      <disposition>none</disposition>
      <dkim>pass</dkim>
      <spf>pass</spf>
    </policy_evaluated>
  </row>
  <identifiers>
    <header_from>senderdomain.com</header_from>
  </identifiers>
  <auth_results>
    
    <spf>
      <domain>senderdomain.com</domain>
      <result>pass</result>
    </spf>
  </auth_results>
</record>
</feedback>
```

this is the one i received, maybe somthing wron in the dmarc config ?

**Comment by vstakhov** [comment]
You might probably have not installed the fix...

**Comment by aalmenar** [comment]
> You might probably have not installed the fix...

yes, this change...

https://github.com/rspamd/rspamd/commit/78a44caf619fd293fcc097e77641b98e76c655fe

Verified again, its there

but running rspamadm dmarc_report -n -v

non of the reports include it

**Comment by vstakhov** [comment]
That's strange as I can clearly see all dkim results, both for dkim failures and passes...

**Comment by aalmenar** [comment]
Nevermind. Restarted the services in the cluster, now its ok.

Sorry for the confusion.

**Comment by PHPGangsta** [comment]
Just a quick question: When will there be a new version with this fix in it? My systems are sending DMARC reports without the DKIM auth result. I currently run:
rspamd 3.0-2~bionic amd64
