### ISSUE TITLE
[Feature] new gpg file and packaging for RHEL9 and derivatives

### ISSUE THREAD

**Issue by shpokas** [rspamd/rspamd#4215]
## Summary

New GPG file is required for RHEL9, new packages for RHEL9 would be great to have as well.

## Details

Current PGP file is not usable on RHEL9 and derivatives (tried on Alma Linux 9.0) due to upstream change [Reject unimplemented critical PGP packets as per RFC-4880](https://github.com/rpm-software-management/rpm/commit/f22499a05d0a01e35dd10d7644f8d74391ba4222)

Would be great to have repo for RHEL 9.0 as it is already out in the wild.

rpm command fails as below

```
# rpm --import https://rspamd.com/rpm-stable/gpg.key -v
error: https://rspamd.com/rpm-stable/gpg.key: key 1 import failed.
```

**Comment by vstakhov** [comment]
Well, I just need to refresh my mind about how to bootstrap centos chroot :) The compiler and the libraries versions are not a problem for this case.

**Comment by shpokas** [comment]
Beyond GPG, I tried to build Rspamd on Alma Linux 9.0, but distro is missing several devel packages so it starts looking complicated to me.
These are:

> 1. file-devel
> 2. lapack-devel
> 3. openblas-devel

**Comment by infinitail** [comment]
use "--enablerepo=crb" option

> Beyond GPG, I tried to build Rspamd on Alma Linux 9.0, but distro is missing several devel packages so it starts looking complicated to me. These are:
> 
> > 1. file-devel
> > 2. lapack-devel
> > 3. openblas-devel

**Comment by istiak101** [comment]
> bootstrap centos chroot

I don't know if you used mock previously but this is a very useful tool to have different chroots with multiple distro configuration.
https://github.com/rpm-software-management/mock

**Comment by shpokas** [comment]
> use "--enablerepo=crb" option
> 
> > Beyond GPG, I tried to build Rspamd on Alma Linux 9.0, but distro is missing several devel packages so it starts looking complicated to me. These are:
> > > 1. file-devel
> > > 2. lapack-devel
> > > 3. openblas-devel

Fantastic! Now I have a package to test and eventually consider migrating to RHEL9/Alma9.

**Comment by r3pek** [comment]
For those of you in need, there's a repo in COPR with rspamd compiled for EL9 and derivatives (installed fine on CentOS 9 Stream [haven't tested it yet])

**Comment by PaweltK** [comment]
> For those of you in need, there's a repo in COPR with rspamd compiled for EL9 and derivatives (installed fine on CentOS 9 Stream [haven't tested it yet])
> 
> https://copr.fedorainfracloud.org/coprs/areiter/centos-stream-9-extra/

I tested on Rocky Linux 9.1 (Blue Onyx) with no success

> 2023-01-31 20:51:43 #200632(normal) rspamd_crash_sig_handler: caught fatal signal 11(Segmentation fault), pid: 200632, trace:
> 2023-01-31 20:51:43 #200632(normal) rspamd_crash_sig_handler: please see Rspamd FAQ to learn how to dump core files and how to fill a bug report
> 2023-01-31 20:51:43 #200527(main) <fafbcd>; main; rspamd_check_termination_clause: normal process 200632 terminated abnormally by signal: Segmentation fault and created core file; please see Rspamd FAQ to learn how to extract data from core file and fill a bug report
> 2023-01-31 20:51:43 #200527(main) <fafbcd>; main; rspamd_cld_handler: respawn process normal in lieu of terminated process with pid 200632

Is there rspamd.spec anywhere to build the current package?

**Comment by whataboutpereira** [comment]
Any progress with EL9?

**Comment by VikingGer** [comment]
> > For those of you in need, there's a repo in COPR with rspamd compiled for EL9 and derivatives (installed fine on CentOS 9 Stream [haven't tested it yet])
> > https://copr.fedorainfracloud.org/coprs/areiter/centos-stream-9-extra/
> 
> I tested on Rocky Linux 9.1 (Blue Onyx) with no success
> 
> > 2023-01-31 20:51:43 #200632(normal) rspamd_crash_sig_handler: caught fatal signal 11(Segmentation fault), pid: 200632, trace:
> > 2023-01-31 20:51:43 #200632(normal) rspamd_crash_sig_handler: please see Rspamd FAQ to learn how to dump core files and how to fill a bug report
> > 2023-01-31 20:51:43 #200527(main) ; main; rspamd_check_termination_clause: normal process 200632 terminated abnormally by signal: Segmentation fault and created core file; please see Rspamd FAQ to learn how to extract data from core file and fill a bug report
> > 2023-01-31 20:51:43 #200527(main) ; main; rspamd_cld_handler: respawn process normal in lieu of terminated process with pid 200632

Did you try it with the newest version 3.5-1.el9?

**Comment by rekup** [comment]
The problem with the GPG key seems to be that it uses SHA1 as signature hash algorithm, which on EL9 due to the default crypto policy. If we change the policy to allow SHA1 hashes using `update-crypto-policies --set DEFAULT:SHA1` (probably a bad idea), the key can be imported. But even with the gpg key imported, the installation of rspamd fails due to mismatching versions of some shared libs.
We would really like to use the official repos instead of the copr repo mentioned above. I'm not sure how the current build process works, but if it helps I can try to update the [`rspamd.spec`](https://github.com/rspamd/rspamd/blob/master/rpm/rspamd.spec) file to make it work with EL9.

**Comment by mean-cj** [comment]
+1 I'm also waiting.

**Comment by SemaiCZE** [comment]
@shpokas @vstakhov why Debian Bookworm is supported a few days after its release and RHEL 9 (including derivates like AlmaLinux) is still not supported after more than a year? If your key is not strong enough, why you can't just make a new one?

**Comment by vstakhov** [comment]
Hum, probably it is because you pay for RHEL 9 packages to RedHat as a part of some support contract and not to Rspamd. However, I see no issues with building packages for this distributive, and I have already added a docker container to do so.

**Comment by vstakhov** [comment]
I have created and published the packages for RHEL9 and derivatives for both stable and experimental branches. Please test.

**Comment by SemaiCZE** [comment]
@vstakhov Hi, I've managed to upgrade my VPS to AlmaLinux 9 and rspamd is working fine. Massive thank you!

**Comment by whataboutpereira** [comment]
Got it nicely running too, however you may want to consider adding an updated GPG for EL9+, because by default they don't allow importing SHA1 signatures any more.

```
warning: Signature not supported. Hash algorithm SHA1 not available.
key 1 import failed.
```

**Comment by sq-gh** [comment]
thanks @vstakhov for building for RHEL9, but like @whataboutpereira mentioned, the package doesn't actually install on a RHEL9 system with default crypto policy due to SHA1 deprecation. 

see: https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9 for more info and for tips on how to tweak the rpm macro to sign with something modern / supported

**Comment by ivanov17** [comment]
I get the following error on CentOS Stream 9 when I install rspamd package:

```
warning: Signature not supported. Hash algorithm SHA1 not available.
error: failed to parse public key for /var/cache/yum/metadata/rspamd-9-x86_64/gpg.key
```

@vstakhov, please, upgrade your repository key to SHA512 or add a new key for CentOS 9 and edit https://rspamd.com/rpm/centos-9/rspamd.repo file. Thank you.

**Comment by istiak101** [comment]
I want to FOSS maintainers write code for me.
Then I want them to build it for me.
Then I want a OS specific package.
Then I want them to sign it the OS specific way.

If you don't I will abuse you.

Thanks FOSS 😍

**Comment by ivanov17** [comment]
@istiak101 According to RedHat Bugzilla there have been at least two attempts to build rspamd package for inclusion in the Fedora repositories, and later in EPEL:

* https://bugzilla.redhat.com/show_bug.cgi?id=1023690
* https://bugzilla.redhat.com/show_bug.cgi?id=1494914

There are some issues with this. Perhaps rspamd mantainers could help resolve them. 

In this case, the packaging and the administration of the repositories could be taken over by the community. Then no one will ask developers about broken keys.

**Comment by istiak101** [comment]
If I remember correctly from my build experience Ragel is a blocker for this. So now the question is why would a maintainer also maintain another package in OS specific repository that's not their responsibility?

Also maintainer builds don't add extra spices to the build. A build is a build. There are already packages in COPR. Nagging maintainers from a project without doing any real thing is absurd in the name of community. Maybe the so called FOSS community can build Ragel in Fedora/EPEL and start from there?

**Comment by ivanov17** [comment]
> If I remember correctly from my build experience Ragel is a blocker for this

I see that the Ragel package is already in the Fedora and EPEL repositories. Maybe there are other problems with Ragel?

> There are already packages in COPR

Yes, there are twenty repositories in COPR that contain the Rspamd package. I think this means that the community is trying to do something to build and package Rspamd for a few specific distributions.

> Nagging maintainers from a project without doing any real thing is absurd in the name of community

Do you want me to create another repository in COPR? 🤔

**Comment by istiak101** [comment]
Go ahead and take the burden of Fedora and EPEL too.

**Comment by vstakhov** [comment]
There is of course an official guide about how to use sha1 signed repos on RHEL9 and derivatives.

**Comment by sq-gh** [comment]
> I want to FOSS maintainers write code for me. Then I want them to build it for me. Then I want a OS specific package. Then I want them to sign it the OS specific way.
> 
> If you don't I will abuse you.
> 
> Thanks FOSS 😍

Nobody is abusing the developers. It is not unreasonable to report issues for a package to the repository maintainers and to offer resources on how to fix it. Especially when the install fails on the target operating system under default configuration.

> There is of course an official guide about how to use sha1 signed repos on RHEL9 and derivatives.

Yes, and it is easy. Unfortunately it is not cryptographically secure.

**Comment by whataboutpereira** [comment]
All this fuss over a puny deal breaking signature file. Personally can't wait for an updated key, so I can restore my AlmaLinux 9 to the contemporary default security level.

**Comment by ivanov17** [comment]
Personally, I have disabled GPG checks for the Rspamd repository because I need to create a container image and I can't install additional python packages with dependencies to enable SHA1 again just to install the package.

I would be happy to contribute my Containerfile to the project if it is useful to someone. But I'm not ready to become a Fedora maintainer right now just to fix a GPG key issue.

I see that @LorbusChris from RedHat was trying to solve some problems with adding the Rspamd package to the Fedora repository. I think it would be useful if he would be so kind as to tell us what issues are still blocking this. Perhaps the Rspamd developers can help solve the issues.

**Comment by LorbusChris** [comment]
For the requirements for official Fedora packaging, see https://bugzilla.redhat.com/show_bug.cgi?id=1494914,
i.e. the remaining TODOs in https://github.com/LorbusChris/rspamd-rpm/blob/master/rspamd.spec (PRs are welcome).

In the meantime the RPM is auto-built here: https://copr.fedorainfracloud.org/coprs/lorbus/rspamd/
EL9 users could use the EPEL9 builds.

**Comment by akansc** [comment]
> There is of course an official guide about how to use sha1 signed repos on RHEL9 and derivatives.

Emm, are you talking about lowering the global security setting in order to install one package?
Or to disable the gpg check completely for the rspamd repo?

I'm not sure I understand why to use workarounds that lowers security when a proper fix is just to use a proper key.

**Comment by fatalbanana** [comment]
It's fixed now I believe.

**Comment by sq-gh** [comment]
> > It doesn't look fixed - As of today I am unable to import https://rspamd.com/rpm-stable/gpg.key (attached below as well) under the DEFAULT security profile with the same error:
> 
> The copy of the key to use is at http://rspamd.com/rpm/gpg.key ; new `.repo` files are pointing there.

Thanks, not sure how i missed that! RHEL-9 is trusting packages in the stable repo now!

**Comment by cgroschupp** [comment]
@vstakhov Can you please reopen this issue as it is not resolved.
