### ISSUE TITLE
[BUG] WebGUI not changing to new tabs

### ISSUE THREAD

**Issue by EasyNetDev** [rspamd/rspamd#4647]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
After the upgrade to 3.7.1 the WebGUI doesn't change to new tabs if is clicked. Tested on Firefox 118.0.1 (64-bit) and Chrome 120.0.6072.0

### Steps to Reproduce

1. Log in to Rspamd WebGUI using a reverse proxy using SSL.
2. Try any of the tabs: 
    Status
    Throughput
    Configuration
    Symbols
    Scan/Learn
    Test selectors
    History
4. The WebGUI remains on same page.

**Expected behavior**
Suppose to change to the new tab.

### Versions

Rspamd daemon version 3.7.1

CPU architecture x86_64; features: avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
Hyperscan enabled: TRUE
Jemalloc enabled: TRUE
LuaJIT enabled: TRUE (LuaJIT version: LuaJIT 2.1.0-beta3)
ASAN enabled: FALSE
BLAS enabled: FALSE
Fasttext enabled: FALSE

OS: Debian GNU/Linux trixie/sid
Kernel: 6.5.0-1-amd64
nginx: 1.24.0-2

Using Nginx config:
```
server {
        listen 8080 ssl;
        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-XSS-Protection "1; mode=block";

#        include ssl.conf;
        ssl_certificate /etc/letsencrypt/live/mx01.mydomain.ext/fullchain.pem;
        ssl_trusted_certificate /etc/letsencrypt/live/mx01.mydomain.ext/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mx01.mydomain.ext/privkey.pem;

        server_name mx01.mydomain.ext;
        location / {
            root /usr/share/rspamd/www/;
            try_files $uri @proxy;
        }
        location @proxy {
                proxy_pass  http://127.0.0.1:11334;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
        }
        location /rspamd/ {
                proxy_pass       http://localhost:11334/;
                proxy_set_header Host      $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        ssl on;
        ssl_protocols TLSv1.2 TLSv1.3;

        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:TLS:10m;
        ssl_session_timeout 1d;
        ssl_stapling on;
        ssl_stapling_verify on;
        server_tokens off;
}
```

**Comment by moisseev** [comment]
Does it work without reverse proxy?

**Comment by EasyNetDev** [comment]
Hi @moisseev ,

I tried right now and it doesn't work. I have 2 servers running 3.7.1 and 1 with 3.7.0. The one with 3.7.0 the WebGUI is still working fine. The other 2 have the same behavior.

I will try to update to 3.7.2 to see if the issue is still persisting.

**Comment by EasyNetDev** [comment]
The only way to see the page is to click on the tab then you have a link like: http://HOST:11334/#history or https://mx01.mydomain.ext:8080/#history and then refresh the page.

**Comment by moisseev** [comment]
I cannot reproduce the problem. It just works.
Could it be because of some browser add-on?

**Comment by EasyNetDev** [comment]
Hm .. same browsers, different rspamd version 3.7.0 is working well.

**Comment by moisseev** [comment]
3.7.0 was never released. Can you refer to the commit of the build?

**Comment by EasyNetDev** [comment]
Sure.

```
# dpkg -l | grep rspamd
ii  rspamd                                  3.7-0~git40~c4e54b4da~bullseye          amd64        Rapid spam filtering system
```

**Comment by moisseev** [comment]
I don't see any suspicious change between c4e54b4 and af3e90f (3.7.1). 🤷‍♂️

**Comment by EasyNetDev** [comment]
Ok. Now I have 1 server running 3.7.2 and the tabs are working again. The server that runs 3.7.1 still have the same behavior that I can't switch between the tabs, and the last server which is running 3.7.0 that can switch between tabs.

**Comment by EasyNetDev** [comment]
I've upgraded also the one with 3.7.1 to 3.7.2. Now is working without issues.

**Comment by EasyNetDev** [comment]
I took the sources from https://rspamd.com/apt/pool/main/r/rspamd/ and I used rspamd_3.7.2-0~git43~8e7b12ede~focal.debian.tar.xz and I changed "focal" to "trixie".

This is my .deb:
rspamd_3.7.2-0~git43~8e7b12ede~trixie_amd64.deb

**Comment by moisseev** [comment]
That's weird. The patch version number is the only difference since 3.7.1.
https://github.com/rspamd/rspamd/compare/3.7.1...8e7b12ede

Probably it somehow related to the packages.

**Comment by EasyNetDev** [comment]
Hm .. could be. I've notice now, after you told me, to check the sources of 3.7.1.
What I'm seeing in debian/patches is this:
```
-rw-r--r-- 1 adrian adrian    439 Mar 21  2023 0001-fix-perl-sheebang.patch
-rw-r--r-- 1 adrian adrian   3172 Oct  8 16:24 0003-add-versions-to-shared-libraries.patch
-rw-r--r-- 1 adrian adrian 420157 Oct  8 16:32 0004-drop-js-scripts-packaged-by-Debian.patch
-rw-r--r-- 1 adrian adrian    681 Oct  8 16:35 0006-do-not-install-fonts-packaged-by-Debian.patch
-rw-r--r-- 1 adrian adrian    170 Jun 25 02:28 series
```

What it triggers me the attention is this patch: `0004-drop-js-scripts-packaged-by-Debian.patch`. Is deleting all jsquery and bootstrap:
```
From: =?utf-8?q?Christian_G=C3=B6ttsche?= <cgzones@googlemail.com>
Date: Wed, 15 Jan 2020 14:36:58 +0100
Subject: drop js scripts packaged by Debian

Also drop version from jquery path to match the Debian version.
---
 interface/css/bootstrap.min.css          | 7 -------
 interface/js/lib/bootstrap.bundle.min.js | 7 -------
 interface/js/lib/jquery-3.6.1.min.js     | 2 --
 interface/js/lib/require.min.js          | 5 -----
 interface/js/main.js                     | 2 +-
 5 files changed, 1 insertion(+), 22 deletions(-)
 delete mode 100644 interface/css/bootstrap.min.css
 delete mode 100644 interface/js/lib/bootstrap.bundle.min.js
 delete mode 100644 interface/js/lib/jquery-3.6.0.min.js
 delete mode 100644 interface/js/lib/require.min.js
```

And it replace it with the one in Debian:

```
--- a/interface/js/main.js
+++ b/interface/js/main.js
@@ -4,7 +4,7 @@ requirejs.config({
     baseUrl: "js/lib",
     paths: {
         app: "../app",
-        jquery: "jquery-3.7.0.min",
+        jquery: "jquery.min",
         visibility: "visibility.min",
         bootstrap: "bootstrap.bundle.min",
         codejar: "codejar.min",
```

JQuery/Bootstrap on my systems:
```
ii  libjs-jquery                       3.6.1+dfsg+~3.5.14-1             all          JavaScript library for dynamic web applications
ii  libjs-bootstrap4                   4.6.1+dfsg1-4                    all          HTML, CSS and JS framework
```

This can explain the issue. Could be the problem of the WebGUI that is not compatible with Debian's jquery/bootstrap?
I see rspamd WebGUI is including jqeury 3.7.0.

**Comment by moisseev** [comment]
> This can explain the issue. Could be the problem of the WebGUI that is not compatible with Debian's jquery/bootstrap?
I see rspamd WebGUI is including jqeury 3.7.0.

... and `Bootstrap v5.3.1`. So, it's not an Rspamd bug.

⚠️ [Debian standard repos notes](https://rspamd.com/downloads.html#debian-standard-repos-notes)

**Comment by NicoloLazzaroni** [comment]
Had the same issue with 3.7.3-1 on Debian 12.
Solved by re-installing libbinutils/stable, which was on a version too high (from the unstable section of the repo) for rspamd, and upgrading to 3.7.4.

**Comment by EasyNetDev** [comment]
Hi @NicoloLazzaroni 

Thanks for the info. Now I'm running 3.8.1 with 2.41.90.20240122-1 and still getting this issue.
Which libbinutils version you use?

**Comment by NicoloLazzaroni** [comment]
> Hi @NicoloLazzaroni
> 
> Thanks for the info. Now I'm running 3.8.1 with 2.41.90.20240122-1 and still getting this issue. Which libbinutils version you use?

Hello,

Sadly the bug also came back to me with version 3.8.1, even running libbinutils form Debian's "stable" repo (v. 2.40-2).

I could fix it by installing rSpamd through their own repo: https://rspamd.com/downloads.html
With their latest version (3.8.4) I don't have this issue anymore.

Hope I've been helpful.

**Comment by vstakhov** [comment]
I don't understand this issue. As it was circulated many times, Debian provided packages are NOT supported by Rspamd, nor recommended for use. If you are brave enough, please try open issues in the Debian bug tracker, but this issue is clearly an off-topic here.

**Comment by EasyNetDev** [comment]
@vstakhov from my side I already opened a bug report to Debian.
I understand your point of view. We just had a simple discussion about this. 
We understand and is not rspamd issue.
