### ISSUE TITLE
[BUG] DKIM bodyhash (bh) calculation fails in relaxed mode because of wrong canonicalization

### ISSUE THREAD

**Issue by PHPGangsta** [rspamd/rspamd#5590]
Hi,

for some emails I wrongly get a R_DKIM_REJECT symbol.

Logs see below, the bodyhash (bh) calculation fails.

**I reproduced the bug:**

The email DKIM signature uses "c=relaxed/relaxed".

The email has a line with only spaces in it (the second last line).

If I take the original email, I get R_DKIM_REJECT.
If I remove those 5 spaces, I get R_DKIM_ALLOW.

It looks like rspamd does not remove those multiple/trailing spaces before calculating the bodyhash.

Here the .eml (I removed lots of headers and anonymized it):
```
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
  d=deutschepost.de; l=578; s=20140901; t=1756196497;
  x=1757492497;
  h=date:from:to:message-id:subject:mime-version:
   content-type:content-transfer-encoding;
  bh=Dban9OxW9ulkvleB/xEttAA+QHXWjMyycEfrb6hJGfI=;
  b=ITFuHu4xhX9cw2ovqzq5Lpc+dwrCCVJNf+S/MQjOAG7JBrB8bKp8Avmq
   l2heuUVsOpb6HCtpoFkz4jwdeX93mvUDBFt5tBSYcFjASVMGVeT0nUus1
   4DbURASE1zJvB56VSVflWolzliVYD4z2u5qEPuAf24O2t43nnGES67pfN
   5IlPLDIvDlrkKfVhs40CIyGthAZNs2T1yJs6kfZ8lAVuw37u9006a37fg
   +TPlFvYEvDN06oExg8aWPqkBFxo4VwyzVYLuPeO2E4c7iaTJMDtYYqsDA
   IFOL6PTEWvjzhmAFjT6GAP1dQnkxbrnscoOOblU9ftztx/iG1oiEvKPMk
   w==;
Received: from unknown (HELO mkp-smtp-client-normal-b689c4596-47n6q) ([10.183.31.144])
  by gateway11l.dhl.com with ESMTP; 26 Aug 2025 08:21:31 +0000
Date: Tue, 26 Aug 2025 10:21:31 +0200 (CEST)
From: E-POST Mailer <noreply@deutschepost.de>
To: info@test.de
Message-ID: <753824802.63464.1756196491419@gateway.dhl.com>
Subject: =?UTF-8?Q?Report:_E-POST_Sendungen_vom_8/25/?=
 =?UTF-8?Q?2025_12:00:00_AM_=C3=BCber_kd5303885638?=
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit
contentType: text/html; charset=UTF-8

<HTML><head></head><BODY>
<font face="Delivery">
Systemmittelung:
Tages-Report 8/25/2025 12:00:00 AM kd5303885638:
<table style="width:100%">
<tr>
<td>0 </td> 
<td>Anzahl Sendungen gesamt</td>
</tr>
<tr>
<td>davon:</td>
<td> </td>
</tr>
<tr>
<td>0 </td> 
<td>Sendungen erfolgreich</td>
</tr>
<tr>
<td>0 </td>
<td>Sendungen fehlgeschlagen</td>
</tr>
<td>0 </td>
<td>Testsendungen</td>


<a href="https://mailer.epost.de//journal/index?s=25-08-2025&e=25-08-2025&">Journalansicht f&#252;r 8/25/2025 12:00:00 AM kd5303885638</a>


     
</font></BODY></HTML>
```

Logfiles of DKIM module (please read from bottom to top):

```
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dmarc; dmarc.lua:182: validated dmarc policy for deutschepost.de: reject; dkim_ok=false, dkim_tempfail=false, spf_ok=false, spf_tempfail=false
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_check: bh value mismatch after added LF: 0db6a7f4ec56f6e964be5781ff112db4003e4075d68cccb27047eb6fa84919f2 versus 725b7949df8e83f1cfe417f49bdad6941367a936172151ff6f9f7329f6cda6be
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_check: bh value mismatch after added CRLF: 0db6a7f4ec56f6e964be5781ff112db4003e4075d68cccb27047eb6fa84919f2 versus eb284cf35f297615cec25ab1300e8a5f8ba90430f0bae8fe5c854bfa29b2e7b5, try add LF
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_check: bh value mismatch: 0db6a7f4ec56f6e964be5781ff112db4003e4075d68cccb27047eb6fa84919f2 versus c34373bed2ab75dcc51a1173d8320220a9d05ef54b8a99f25928fe8cc94348bc, try add LF; try adding CRLF
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_signature_update: final update hash with signature part: ;
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_signature_update: initial update hash with signature part: dkim-signature:v=1; a=rsa-sha256; c=relaxed/relaxed; d=deutschepost.de; l=578; s=20140901; t=1756196497; x=1757492497; h=date:from:to:message-id:subject:mime-version: content-type:content-transfer-encoding; bh=Dban9OxW9ulkvleB/xEttAA+QHXWjMyycEfrb6hJGfI=; b=
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header (idx=0): content-transfer-encoding:7bit
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header (idx=0): content-type:text/html; charset=UTF-8
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header (idx=0): mime-version:1.0
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header (idx=0): subject:=?UTF-8?Q?Report:_E-POST_Sendungen_vom_8/25/?= =?UTF-8?Q?2025_12:00:00_AM_=C3=BCber_kd5303885638?=
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header (idx=0): message-id:<753824802.63464.1756196491419@gateway.dhl.com>
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header (idx=0): to:info@test.de
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header (idx=0): from:E-POST Mailer <noreply@deutschepost.de>
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_canonize_header_relaxed: update signature with header (idx=0): date:Tue, 26 Aug 2025 10:21:31 +0200 (CEST)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (20 size, 20 -> 0 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (2 size, 23 -> 20 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (2 size, 25 -> 23 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (2 size, 27 -> 25 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (140 size, 167 -> 27 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (2 size, 169 -> 167 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (2 size, 171 -> 169 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (24 size, 195 -> 171 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (13 size, 208 -> 195 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (7 size, 215 -> 208 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (35 size, 250 -> 215 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (13 size, 263 -> 250 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (6 size, 269 -> 263 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (7 size, 276 -> 269 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (32 size, 308 -> 276 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (13 size, 322 -> 308 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (6 size, 328 -> 322 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (7 size, 335 -> 328 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (12 size, 347 -> 335 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (17 size, 364 -> 347 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (6 size, 370 -> 364 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (7 size, 377 -> 370 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (34 size, 411 -> 377 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (13 size, 425 -> 411 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (6 size, 431 -> 425 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (28 size, 459 -> 431 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (50 size, 509 -> 459 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (18 size, 527 -> 509 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (24 size, 551 -> 527 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_dkim_relaxed_body_step: relaxed update signature with body buffer (27 size, 578 -> 551 remain)
2025-08-26 11:34:27 #1024393(controller) <e57abe>; dkim; rspamd_create_dkim_context: create dkim context sig = 2900939125062359084
```

opendkim says the signature is valid:
```
Aug 26 12:26:01 mxpostfix01 opendkim[1742]: BDF4D240BF2: s=20140901 d=deutschepost.de a=rsa-sha256 SSL
Aug 26 12:26:01 mxpostfix01 opendkim[1742]: BDF4D240BF2: DKIM verification successful
```
Gmail also says the DKIM signature is valid:
```
Authentication-Results: mx.google.com;
       dkim=pass header.i=@deutschepost.de header.s=20140901 header.b=ITFuHu4x;
       spf=pass (google.com: domain of mail@test.de designates 2a01:4f8:c2c:xxxx::xxxx as permitted sender) smtp.mailfrom=mail@test.de;
       dmarc=pass (p=REJECT sp=REJECT dis=NONE) header.from=deutschepost.de
```
Microsoft also says dkim=pass:
```
Authentication-Results: spf=pass (sender IP is 2a01:4f8:c2c:xxxx::xxxx)
 smtp.mailfrom=test.de; dkim=pass (signature was verified)
 header.d=deutschepost.de;dmarc=pass action=none
 header.from=deutschepost.de;compauth=pass reason=100
```

It looks like the problem are the spaces that are not removed before calculating the bodyhash.

**Comment by frickl** [comment]
also seen - only with one special selector s=20140901 :

Aug 26:
..rspamd[86956]: <2fa76f>; dkim; rspamd_dkim_check: bh value mismatch: f929693b92b234f5ea4511306a3a0a943b918dd89a2aabf43de988de841fb007 versus 9993ebccf8c15bbb38db47fbfb6fec369ecab13b8a80b4d9595c49fe4ca9ecb3, try add LF; try adding CRLF
..rspamd[86956]: <2fa76f>; dkim; rspamd_dkim_check: bh value mismatch after added CRLF: f929693b92b234f5ea4511306a3a0a943b918dd89a2aabf43de988de841fb007 versus 53ff8ee14d99b011b51ae800c1fb3d530c655a252d8841eb7deadf29ad42e3dd, try add LF
..rspamd[86956]: <2fa76f>; dkim; rspamd_dkim_check: bh value mismatch after added LF: f929693b92b234f5ea4511306a3a0a943b918dd89a2aabf43de988de841fb007 versus 95fed47001c8ec842347a031c244e0d3ad467dbe9e7b0c7ffa1fbccf16e0e490
..rspamd[86956]: <2fa76f>; dkim; rspamd_dkim_check: dkim: bh value mismatch: got mZPrzPjBW7s420f7+2/sNp7KsTuKgLTZWVxJ/kyp7LM=, expected +SlpO5KyNPXqRREwajoKlDuRjdiaKqv0PemI3oQfsAc=; body length 585->575; d=deutschepost.de; s=20140901

**Comment by PHPGangsta** [comment]
I have another email with the same problem:

The email body only has a single space in it. rspamd says the DKIM signature is invalid, other DKIM verifier say it's valid. If I remove that single space, then rspamd also says it's valid. Body canonicalization seems to not work properly for "relaxed".

Probably it's this:

RFC 6376 section 3.4.4 for "relaxed body canonicalization":
```
- Ignore all whitespace at the end of lines.  Implementations MUST NOT remove the CRLF at the end of the line.
```
https://datatracker.ietf.org/doc/html/rfc6376#section-3.4.4

**Comment by vstakhov** [comment]
Can you please zip this sample, as github apparently breaks something

**Comment by PHPGangsta** [comment]
Hi,

here you are:
[email_for_issue.zip](https://github.com/user-attachments/files/22044714/email_for_issue.zip)

As said, I had to anonymize the "To:"-header because it's a customer email address.. The full DKIM Signature will be invalid because of that. But to show the problem with the bodyhash the headers are not important.

**Comment by vstakhov** [comment]
Ok, the issue is in fact with l=578 not with 5 spaces.

**Comment by vstakhov** [comment]
Ok, I have fixed that in #5593

**Comment by PHPGangsta** [comment]
Thank you very much!!

**Comment by PHPGangsta** [comment]
Sorry I have to reopen this issue. I updated to rspamd 3.13 (and to 3.13.1 in a test environment), and most of the problems are fixed.

But one email still fails (in both 3.13.x versions), which I reported in comment https://github.com/rspamd/rspamd/issues/5590#issuecomment-3232213674

If the email only has a single space in the body, then rspamd says "dkim=fail", whereas opendkim, Microsoft and Gmail say "dkim=pass".

Maybe there is another small bug regarding relaxed body canonicalization in this special case?

The "bh" value in the DKIM signature is: `47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=`

```
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; t=1759441530;
    s=XXXXXX-dkim-0002; d=XXXXX.berlin;
    h=Date:Message-Id:Subject:To:From:Cc:Date:From:Subject:Sender;
    bh=47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=;
    b=tiWAACnRobdI08LjAVzkdCY5GsQ7BVMmds+mddyab42nh17xVBRpBO0OOQ1fkYqtGI
    jKj8Pf0iKb+SAspypTnTceVew93AQ9pSvNeZPnpXYK2Ze5Dl/6sA6HTUNfHfY7CZFy2O
    iwRi1B4QOrjqq0iY/fn2wAbaE5ZYa80vaY51+rOI+9tDuJHkee/l/sjQhxjAq17SsJds
    mmX92egUzvGXs8l/faCrmo6SOVjv4eMqMlrP/XDmnJpjRQBpA47FeUGn/DP+2iG75Uw3
    XLFQ0fLGcAhJ54pdCJS9GcNPZ/bfWFP154mg17+KTNCQrpxPUF6mTCVsh8fQGPHkFK+f
    aotg==
```

The body only has a single space in it.

Can you please have a look?

**Comment by vstakhov** [comment]
Can you please make .eml sample zipped in the archive as spaces handling in github are a bit clumsy?

**Comment by PHPGangsta** [comment]
Hi. 

I hope this zip with the .eml in it triggers it, I had to redact+remove lots of headers. But the important part is the body with just a single space in it.

[email_only_with_space.zip](https://github.com/user-attachments/files/22680614/email_only_with_space.zip)

**Comment by PHPGangsta** [comment]
Interesting: If I copy&paste the email with the single space in the body to the rspamd WebGUI->Scan/Learn, it says the DKIM-Signature is valid. If I send the exact same .eml via Telnet to a Postfix (with opendkim and rspamd connected as milters), then opendkim says "dkim=pass" and rspamd says "dkim=fail". If I do the exact same Telnet to Gmail or Microsoft, they also say "dkim=pass". rspamd behaves differently in SMTP/Milter context compared to the others.

**Comment by PHPGangsta** [comment]
[email_only_with_space_and_linebreak.zip](https://github.com/user-attachments/files/22681997/email_only_with_space_and_linebreak.zip)

This .eml also triggers the problem. It has a space and a linebreak.

In RFC 6376 there is an example with an empty body after relaxed body canonicalization:

https://datatracker.ietf.org/doc/html/rfc6376#section-3.4.4

>    a.  Reduce whitespace:
>       *  Ignore all whitespace at the end of lines.  Implementations MUST NOT remove the CRLF at the end of the line.
>       *  Reduce all sequences of WSP within a line to a single SP character.
> 
>    b.  Ignore all empty lines at the end of the message body.  "Empty line" is defined in Section 3.4.3.  If the body is non-empty but does not end with a CRLF, a CRLF is added.  (For email, this is only possible when using extensions to SMTP or non-SMTP transport mechanisms.)
> 
>    The SHA-1 value (in base64) for an empty body (canonicalized to a null input) is:
> 
>    2jmj7l5rSw0yVb/vlWAYkK/YBwk=
> 
>    The SHA-256 value is:
> 
>    47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=

The hash `47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=` is the one in the DKIM signature. But rspamd calculates other bodyhashes for an "empty body":

```
2025-10-03 15:40:18 [debug] #2880201(normal) <625f82>; dkim; rspamd_dkim_signature_update: initial update hash with signature part: dkim-signature:v=1; a=rsa-sha256; c=relaxed/relaxed; t=1759441530; s=XXXXXX-dkim-0002; d=XXXXXX.berlin; h=Date:Message-Id:Subject:To:From:Cc:Date:From:Subject:Sender; bh=47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=; b=
2025-10-03 15:40:18 [debug] #2880201(normal) <625f82>; dkim; rspamd_dkim_check: bh value mismatch: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 versus 7eb70257593da06f682a3ddda54a9d260d4fc514f645237f5ca74b08f8da61a6, try add LF; try adding CRLF
2025-10-03 15:40:18 [debug] #2880201(normal) <625f82>; dkim; rspamd_dkim_check: bh value mismatch after added CRLF: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 versus dba5166ad9db9ba648c1032ebbd34dcd0d085b50023b839ef5c68ca1db93a563, try add LF
2025-10-03 15:40:18 [debug] #2880201(normal) <625f82>; dkim; rspamd_dkim_check: bh value mismatch after added LF: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 versus 2a5222a0dd2400f31aae17bc0ad61e08446faa9e86bc9862ba8b0740cfa05283
```
